import { Stock } from "./types";

export const STOCKS: Stock[] = [
    {
        id: 1,
        symbol: "RELIANCE",
        name: "Reliance Industries Ltd",
        sector: "Conglomerate",
        exchange: "NSE",
        price: 2900.50,
        changePercent: 1.25,
        marketCap: "19.5T",
        peRatio: 24.3,
        volume: 3200000,
        volatility: "Medium",
        oneYearReturn: 18.2,
        description: "Reliance Industries Limited is an Indian multinational conglomerate headquartered in Mumbai. Its businesses include energy, petrochemicals, natural gas, retail, telecommunications, mass media, and textiles.",
        sectorTag: "NIFTY 50",
        isFno: true,
        riskLabel: "Moderate"
    },
    {
        id: 2,
        symbol: "TCS",
        name: "Tata Consultancy Services",
        sector: "IT Services",
        exchange: "NSE",
        price: 3450.20,
        changePercent: -0.45,
        marketCap: "12.6T",
        peRatio: 29.1,
        volume: 1500000,
        volatility: "Low",
        oneYearReturn: 12.5,
        description: "Tata Consultancy Services is an Indian multinational information technology services and consulting company headquartered in Mumbai.",
        sectorTag: "NIFTY 50",
        isFno: true,
        riskLabel: "Low"
    },
    {
        id: 3,
        symbol: "HDFCBANK",
        name: "HDFC Bank Ltd",
        sector: "Banking",
        exchange: "NSE",
        price: 1580.00,
        changePercent: 0.80,
        marketCap: "9.5T",
        peRatio: 18.2,
        volume: 4500000,
        volatility: "Medium",
        oneYearReturn: 5.4,
        description: "HDFC Bank Limited is an Indian banking and financial services company headquartered in Mumbai. It is India's largest private sector bank by assets.",
        sectorTag: "NIFTY 50",
        isFno: true,
        riskLabel: "Low"
    },
    {
        id: 4,
        symbol: "INFY",
        name: "Infosys Ltd",
        sector: "IT Services",
        exchange: "NSE",
        price: 1420.75,
        changePercent: 1.10,
        marketCap: "5.9T",
        peRatio: 22.5,
        volume: 2800000,
        volatility: "Medium",
        oneYearReturn: 8.9,
        description: "Infosys Limited is an Indian multinational information technology company that provides business consulting, information technology and outsourcing services.",
        sectorTag: "NIFTY 50",
        isFno: true,
        riskLabel: "Moderate"
    },
    {
        id: 5,
        symbol: "ICICIBANK",
        name: "ICICI Bank Ltd",
        sector: "Banking",
        exchange: "NSE",
        price: 930.50,
        changePercent: 2.10,
        marketCap: "6.5T",
        peRatio: 19.8,
        volume: 3800000,
        volatility: "Medium",
        oneYearReturn: 15.6,
        description: "ICICI Bank Limited is an Indian multinational bank and financial services company headquartered in Mumbai.",
        sectorTag: "NIFTY 50",
        isFno: true,
        riskLabel: "Moderate"
    },
    {
        id: 6,
        symbol: "HINDUNILVR",
        name: "Hindustan Unilever Ltd",
        sector: "FMCG",
        exchange: "NSE",
        price: 2500.00,
        changePercent: -0.20,
        marketCap: "5.8T",
        peRatio: 55.4,
        volume: 800000,
        volatility: "Low",
        oneYearReturn: 3.2,
        description: "Hindustan Unilever Limited is an Indian consumer goods company headquartered in Mumbai. It is a subsidiary of the British company Unilever.",
        sectorTag: "NIFTY 50",
        isFno: true,
        riskLabel: "Low"
    },
    {
        id: 7,
        symbol: "ITC",
        name: "ITC Ltd",
        sector: "FMCG",
        exchange: "NSE",
        price: 440.30,
        changePercent: 0.15,
        marketCap: "5.5T",
        peRatio: 26.7,
        volume: 6500000,
        volatility: "Low",
        oneYearReturn: 28.5,
        description: "ITC Limited is an Indian conglomerate company headquartered in Kolkata. Its diversified business includes FMCG, Hotels, Packaging, Paperboards & Specialty Papers and Agri-Business.",
        sectorTag: "NIFTY 50",
        isFno: true,
        riskLabel: "Low"
    },
    {
        id: 8,
        symbol: "SBIN",
        name: "State Bank of India",
        sector: "Banking",
        exchange: "NSE",
        price: 590.25,
        changePercent: 1.50,
        marketCap: "5.2T",
        peRatio: 10.5,
        volume: 7200000,
        volatility: "Medium",
        oneYearReturn: 19.8,
        description: "State Bank of India is an Indian multinational public sector bank and financial services statutory body headquartered in Mumbai.",
        sectorTag: "NIFTY 50",
        isFno: true,
        riskLabel: "Moderate"
    },
    {
        id: 9,
        symbol: "BHARTIARTL",
        name: "Bharti Airtel Ltd",
        sector: "Telecom",
        exchange: "NSE",
        price: 880.60,
        changePercent: 0.55,
        marketCap: "5.1T",
        peRatio: 45.2,
        volume: 2100000,
        volatility: "Medium",
        oneYearReturn: 22.4,
        description: "Bharti Airtel Limited is an Indian multinational telecommunications services company based in New Delhi.",
        sectorTag: "NIFTY 50",
        isFno: true,
        riskLabel: "Moderate"
    },
    {
        id: 10,
        symbol: "KOTAKBANK",
        name: "Kotak Mahindra Bank",
        sector: "Banking",
        exchange: "NSE",
        price: 1750.80,
        changePercent: -1.10,
        marketCap: "3.5T",
        peRatio: 22.1,
        volume: 1200000,
        volatility: "Medium",
        oneYearReturn: -2.5,
        description: "Kotak Mahindra Bank Limited is an Indian banking and financial services company headquartered in Mumbai.",
        sectorTag: "NIFTY 50",
        isFno: true,
        riskLabel: "Medium"
    },
    {
        id: 11,
        symbol: "LT",
        name: "Larsen & Toubro Ltd",
        sector: "Construction",
        exchange: "NSE",
        price: 2950.40,
        changePercent: 2.30,
        marketCap: "4.1T",
        peRatio: 32.5,
        volume: 1800000,
        volatility: "Medium",
        oneYearReturn: 35.6,
        description: "Larsen & Toubro Ltd is an Indian multinational conglomerate company, with business interests in engineering, construction, manufacturing, technology and financial services.",
        sectorTag: "NIFTY 50",
        isFno: true,
        riskLabel: "Medium"
    },
    {
        id: 12,
        symbol: "AXISBANK",
        name: "Axis Bank Ltd",
        sector: "Banking",
        exchange: "NSE",
        price: 980.15,
        changePercent: 1.05,
        marketCap: "3.0T",
        peRatio: 14.8,
        volume: 3100000,
        volatility: "High",
        oneYearReturn: 10.2,
        description: "Axis Bank Limited is an Indian banking and financial services company headquartered in Mumbai.",
        sectorTag: "NIFTY 50",
        isFno: true,
        riskLabel: "High"
    },
    {
        id: 13,
        symbol: "ASIANPAINT",
        name: "Asian Paints Ltd",
        sector: "Consumer Durables",
        exchange: "NSE",
        price: 3100.90,
        changePercent: 0.30,
        marketCap: "2.9T",
        peRatio: 65.4,
        volume: 600000,
        volatility: "Low",
        oneYearReturn: 4.5,
        description: "Asian Paints Limited is an Indian multinational paint company headquartered in Mumbai.",
        sectorTag: "NIFTY 50",
        isFno: true,
        riskLabel: "Low"
    },
    {
        id: 14,
        symbol: "MARUTI",
        name: "Maruti Suzuki India",
        sector: "Automobile",
        exchange: "NSE",
        price: 9500.00,
        changePercent: 0.90,
        marketCap: "2.8T",
        peRatio: 28.5,
        volume: 500000,
        volatility: "Medium",
        oneYearReturn: 14.8,
        description: "Maruti Suzuki India Limited is an Indian automobile manufacturer based in New Delhi.",
        sectorTag: "NIFTY 50",
        isFno: true,
        riskLabel: "Moderate"
    },
    {
        id: 15,
        symbol: "SUNPHARMA",
        name: "Sun Pharma Inds.",
        sector: "Pharma",
        exchange: "NSE",
        price: 1120.45,
        changePercent: -0.75,
        marketCap: "2.7T",
        peRatio: 30.2,
        volume: 1300000,
        volatility: "Medium",
        oneYearReturn: 25.4,
        description: "Sun Pharmaceutical Industries Limited is an Indian multinational pharmaceutical company headquartered in Mumbai.",
        sectorTag: "NIFTY 50",
        isFno: true,
        riskLabel: "Moderate"
    },
    {
        id: 16,
        symbol: "TITAN",
        name: "Titan Company Ltd",
        sector: "Consumer Durables",
        exchange: "NSE",
        price: 2980.60,
        changePercent: 1.40,
        marketCap: "2.6T",
        peRatio: 75.1,
        volume: 900000,
        volatility: "Medium",
        oneYearReturn: 18.9,
        description: "Titan Company Limited is an Indian luxury products company that mainly manufactures fashion accessories such as jewellery, watches and eyewear.",
        sectorTag: "NIFTY 50",
        isFno: true,
        riskLabel: "Moderate"
    },
    {
        id: 17,
        symbol: "BAJFINANCE",
        name: "Bajaj Finance Ltd",
        sector: "Finance",
        exchange: "NSE",
        price: 7100.20,
        changePercent: 3.10,
        marketCap: "4.3T",
        peRatio: 35.6,
        volume: 1100000,
        volatility: "High",
        oneYearReturn: 20.1,
        description: "Bajaj Finance Limited is an Indian non-banking financial company headquartered in Pune.",
        sectorTag: "NIFTY 50",
        isFno: true,
        riskLabel: "High"
    },
    {
        id: 18,
        symbol: "ULTRACEMCO",
        name: "UltraTech Cement",
        sector: "Construction",
        exchange: "NSE",
        price: 8200.50,
        changePercent: 0.60,
        marketCap: "2.4T",
        peRatio: 38.2,
        volume: 400000,
        volatility: "Medium",
        oneYearReturn: 16.5,
        description: "UltraTech Cement Limited is an Indian cement company based in Mumbai.",
        sectorTag: "NIFTY 50",
        isFno: true,
        riskLabel: "Moderate"
    },
    {
        id: 19,
        symbol: "NESTLEIND",
        name: "Nestle India Ltd",
        sector: "FMCG",
        exchange: "NSE",
        price: 22000.00,
        changePercent: -0.10,
        marketCap: "2.1T",
        peRatio: 80.5,
        volume: 50000,
        volatility: "Low",
        oneYearReturn: 9.8,
        description: "Nestlé India Limited is the Indian subsidiary of Nestlé which is a Swiss multinational food and drink processing conglomerate corporation.",
        sectorTag: "NIFTY 50",
        isFno: true,
        riskLabel: "Low"
    },
    {
        id: 20,
        symbol: "WIPRO",
        name: "Wipro Ltd",
        sector: "IT Services",
        exchange: "NSE",
        price: 405.80,
        changePercent: 0.95,
        marketCap: "2.1T",
        peRatio: 19.4,
        volume: 2500000,
        volatility: "Medium",
        oneYearReturn: -5.2,
        description: "Wipro Limited is an Indian multinational corporation that provides information technology, consulting and business process services.",
        sectorTag: "NIFTY 50",
        isFno: true,
        riskLabel: "Medium"
    },
    {
        id: 21,
        symbol: "M&M",
        name: "Mahindra & Mahindra",
        sector: "Automobile",
        exchange: "NSE",
        price: 1550.30,
        changePercent: 1.80,
        marketCap: "1.9T",
        peRatio: 18.5,
        volume: 2200000,
        volatility: "Medium",
        oneYearReturn: 28.4,
        description: "Mahindra & Mahindra Limited is an Indian multinational automotive manufacturing corporation headquartered in Mumbai.",
        sectorTag: "NIFTY 50",
        isFno: true,
        riskLabel: "Moderate"
    },
    {
        id: 22,
        symbol: "TATAMOTORS",
        name: "Tata Motors Ltd",
        sector: "Automobile",
        exchange: "NSE",
        price: 640.50,
        changePercent: 2.50,
        marketCap: "2.1T",
        peRatio: 45.8,
        volume: 5500000,
        volatility: "High",
        oneYearReturn: 55.2,
        description: "Tata Motors Limited is an Indian multinational automotive manufacturing company headquartered in Mumbai.",
        sectorTag: "NIFTY 50",
        isFno: true,
        riskLabel: "High"
    },
    {
        id: 23,
        symbol: "ADANIENT",
        name: "Adani Enterprises",
        sector: "Services",
        exchange: "NSE",
        price: 2450.00,
        changePercent: -1.50,
        marketCap: "2.8T",
        peRatio: 95.2,
        volume: 3500000,
        volatility: "High",
        oneYearReturn: 12.5,
        description: "Adani Enterprises Limited is an Indian multinational publicly listed holding company and a part of Adani Group.",
        sectorTag: "NIFTY 50",
        isFno: true,
        riskLabel: "High"
    },
    {
        id: 24,
        symbol: "POWERGRID",
        name: "Power Grid Corp",
        sector: "Energy",
        exchange: "NSE",
        price: 210.40,
        changePercent: 0.45,
        marketCap: "1.9T",
        peRatio: 12.5,
        volume: 8500000,
        volatility: "Low",
        oneYearReturn: 15.2,
        description: "Power Grid Corporation of India Limited is an Indian central public sector undertaking under the ownership of the Ministry of Power.",
        sectorTag: "NIFTY 50",
        isFno: true,
        riskLabel: "Low"
    },
    {
        id: 25,
        symbol: "NTPC",
        name: "NTPC Ltd",
        sector: "Energy",
        exchange: "NSE",
        price: 235.60,
        changePercent: 0.85,
        marketCap: "2.3T",
        peRatio: 11.2,
        volume: 6800000,
        volatility: "Low",
        oneYearReturn: 32.5,
        description: "NTPC Limited is an Indian central public sector undertaking under the ownership of the Ministry of Power.",
        sectorTag: "NIFTY 50",
        isFno: true,
        riskLabel: "Low"
    },
    {
        id: 26,
        symbol: "JSWSTEEL",
        name: "JSW Steel Ltd",
        sector: "Metals",
        exchange: "NSE",
        price: 780.20,
        changePercent: 1.15,
        marketCap: "1.9T",
        peRatio: 16.5,
        volume: 1800000,
        volatility: "High",
        oneYearReturn: 11.2,
        description: "JSW Steel Limited is an Indian multinational steel making company based in Mumbai.",
        sectorTag: "NIFTY 50",
        isFno: true,
        riskLabel: "High"
    },
    {
        id: 27,
        symbol: "TATASTEEL",
        name: "Tata Steel Ltd",
        sector: "Metals",
        exchange: "NSE",
        price: 115.40,
        changePercent: 0.75,
        marketCap: "1.4T",
        peRatio: 8.5,
        volume: 4500000,
        volatility: "High",
        oneYearReturn: 8.5,
        description: "Tata Steel Limited is an Indian multinational steel-making company based in Jamshedpur and headquartered in Mumbai.",
        sectorTag: "NIFTY 50",
        isFno: true,
        riskLabel: "High"
    },
    {
        id: 28,
        symbol: "HCLTECH",
        name: "HCL Technologies",
        sector: "IT Services",
        exchange: "NSE",
        price: 1180.50,
        changePercent: 0.85,
        marketCap: "3.2T",
        peRatio: 22.4,
        volume: 2100000,
        volatility: "Medium",
        oneYearReturn: 18.5,
        description: "HCL Technologies Limited is an Indian multinational information technology services and consulting company headquartered in Noida.",
        sectorTag: "NIFTY 50",
        isFno: true,
        riskLabel: "Medium"
    },
    {
        id: 29,
        symbol: "ONGC",
        name: "ONGC Ltd",
        sector: "Energy",
        exchange: "NSE",
        price: 185.30,
        changePercent: -0.65,
        marketCap: "2.3T",
        peRatio: 6.5,
        volume: 7500000,
        volatility: "Medium",
        oneYearReturn: 14.2,
        description: "Oil and Natural Gas Corporation is an Indian central public sector undertaking under the ownership of the Ministry of Petroleum and Natural Gas.",
        sectorTag: "NIFTY 50",
        isFno: true,
        riskLabel: "Moderate"
    },
    {
        id: 30,
        symbol: "COALINDIA",
        name: "Coal India Ltd",
        sector: "Mining",
        exchange: "NSE",
        price: 245.80,
        changePercent: 1.25,
        marketCap: "1.5T",
        peRatio: 7.8,
        volume: 5800000,
        volatility: "Medium",
        oneYearReturn: 22.5,
        description: "Coal India Limited is an Indian central public sector undertaking under the ownership of the Ministry of Coal.",
        sectorTag: "NIFTY 50",
        isFno: true,
    },
    {
        id: 31,
        symbol: "AAPL",
        name: "Apple Inc.",
        sector: "Technology",
        exchange: "NASDAQ",
        price: 180.50,
        changePercent: 1.25,
        marketCap: "3.2T",
        peRatio: 28.5,
        volume: 98000000,
        volatility: "Medium",
        oneYearReturn: 35.2,
        description: "Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide.",
        sectorTag: "US Tech",
        isFno: true,
        riskLabel: "Moderate"
    },
    {
        id: 32,
        symbol: "TSLA",
        name: "Tesla Inc.",
        sector: "Automotive",
        exchange: "NASDAQ",
        price: 240.20,
        changePercent: 2.10,
        marketCap: "800B",
        peRatio: 55.4,
        volume: 125000000,
        volatility: "High",
        oneYearReturn: 15.6,
        description: "Tesla, Inc. designs, develops, manufactures, leases, and sells electric vehicles, and energy generation and storage systems in the United States, China, and internationally.",
        sectorTag: "US Tech",
        isFno: true,
        riskLabel: "High"
    }
];
